import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {EventEmitter} from 'node:events';import {performance} from 'node:perf_hooks';import {attachHealthTelemetry} from '../health-telemetry.mjs';
function response(){const r=new EventEmitter();r.headers={};r.setHeader=(k,v)=>r.headers[k]=v;return r;}
test('health-only metadata records accept, dispatch and prior finish without touching headers or auth',()=>{const s=new EventEmitter();let t=0,us=0;const a=attachHealthTelemetry(s,{mono:()=>t,wall:()=>new Date(1700000000000+t).toISOString(),cpu:()=>({user:us,system:0}),memory:()=>({rss:12345}),elu:()=>({active:t/2,idle:t/2}),pid:42});const socket={};s.emit('connection',socket);t=5;const req={[Symbol.for('dsh.http.authenticated')]:true,method:'GET',url:'/health',socket,get headers(){throw Error('credentials_forbidden')}};const r=response();s.emit('request',req,r);assert.equal(r.headers['x-dsh-health-parse-wait-ms'],'5.000');assert.equal(r.headers['x-dsh-health-pid'],'42');t=35;us=8;r.emit('finish');const r2=response();t=40;s.emit('request',req,r2);assert.equal(r2.headers['x-dsh-health-previous-handler-ms'],'30.000');assert.equal(r2.headers['x-dsh-health-previous-cpu-us'],'8');a.detach()});
test('non-health GET and synthetic model POST are left untouched',()=>{const s=new EventEmitter();const a=attachHealthTelemetry(s,{cpu:()=>{throw Error('should_not_observe')}});for(const req of [{method:'POST',url:'/v1/chat/completions'},{method:'GET',url:'/status'}]){const r=response();s.emit('request',req,r);assert.deepEqual(r.headers,{})}a.detach()});
test('no timers or periodic wakeups are installed',()=>{const original=globalThis.setInterval;globalThis.setInterval=()=>{throw Error('periodic_probe_forbidden')};try{const s=new EventEmitter();const a=attachHealthTelemetry(s);a.detach()}finally{globalThis.setInterval=original}});
test('duplicate attach is rejected, detach permits explicit reattach',()=>{const s=new EventEmitter();const a=attachHealthTelemetry(s);assert.throws(()=>attachHealthTelemetry(s),/already_attached/);a.detach();const b=attachHealthTelemetry(s);b.detach();assert.equal(s.listenerCount('request'),0);assert.equal(s.listenerCount('connection'),0)});
test('does not invent socket acceptance for an unseen connection',()=>{const s=new EventEmitter();const a=attachHealthTelemetry(s);const r=response();s.emit('request',{method:'GET',url:'/health',socket:{}},r);assert.equal(r.headers['x-dsh-health-accept-at'],undefined);a.detach()});
test('existing response body and status survive instrumentation',async()=>{const s=http.createServer((req,res)=>{req[Symbol.for('dsh.http.authenticated')]=true;res.writeHead(200,{'content-type':'application/json'});res.end('{"status":"ok","fixture":true}')});const a=attachHealthTelemetry(s);await new Promise(r=>s.listen(0,'127.0.0.1',r));try{const r=await fetch('http://127.0.0.1:'+s.address().port+'/health');assert.equal(r.status,200);assert.deepEqual(await r.json(),{status:'ok',fixture:true});assert(r.headers.get('x-dsh-health-accept-at'));assert(r.headers.get('x-dsh-health-dispatch-at'))}finally{a.detach();s.closeAllConnections();await new Promise(r=>s.close(r))}});
test('synchronous handler delay is reported separately from acceptance on the next health GET',async()=>{let first=true;const s=http.createServer((req,res)=>{req[Symbol.for('dsh.http.authenticated')]=true;if(first){first=false;const until=performance.now()+45;while(performance.now()<until){}}res.end('{"status":"ok"}')});const a=attachHealthTelemetry(s);await new Promise(r=>s.listen(0,'127.0.0.1',r));try{await (await fetch('http://127.0.0.1:'+s.address().port+'/health')).text();const r=await fetch('http://127.0.0.1:'+s.address().port+'/health');await r.text();assert(Number(r.headers.get('x-dsh-health-previous-handler-ms'))>=40);assert(Number(r.headers.get('x-dsh-health-parse-wait-ms'))>=0)}finally{a.detach();s.closeAllConnections();await new Promise(r=>s.close(r))}});

test('public health reveals no timing or process headers',()=>{const s=new EventEmitter();const a=attachHealthTelemetry(s);const r=response();s.emit('request',{method:'GET',url:'/health',socket:{}},r);assert.deepEqual(r.headers,{});a.detach()});
